const data = {
  products: [
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 160,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'A red t-shirt, perfect for days with non-red weather.',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'A red t-shirt, perfect for days with non-red weather.',
    },
    {
      name: 'Normal Shirt',
      slug: 'normal-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 80,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'A red t-shirt, perfect for days with non-red weather.',
    },
    {
        name: 'Slim Shirt',
        slug: 'full shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 160,
        countInStock: 6,
        brand: 'vans',
        rating: 4.5,
        numReviews: 10,
        description: 'A red t-shirt, perfect for days with non-red weather.',
        },
    {
        name: 'Slim Shirt1',
        slug: 'full shirt1',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 160,
        countInStock: 6,
        brand: 'vans',
        rating: 4.5,
        numReviews: 10,
        description: 'A red t-shirt, perfect for days with non-red weather.',
        },
  ],
};
export default data;